namespace NueGames.NueDeck.Scripts.Enums
{
    public enum AudioActionType
    {
        Attack,
        CityDamaged,
        Push,
        Button,
        Draw,
        Drink,
        EnemyDeath,
        Heal,
        Poison,
        Power,
        Swing,
        CombatMusic,
        CardPlayed,
        CardHovered,
        MenuMusic,
        MeteorBegin,
        MeteorEnd,
        PortalSpawn,
        HandellActivation,
        CardGrabbed,
        Incantation,
        FireAttack,
        WindAttack,
        ThunderAttack,
        IceAttack,
        WaterAttack,
        EarthAttack,
        HandellMunch,
        CardDefault,
        None
    }
}