namespace NueGames.NueDeck.Scripts.Enums
{
    public enum CardActionType
    {
        Attack,
        Heal,
        Block,
        Power,
        IncreaseMaxHealth,
        Draw,
        EarnMana,
        LifeSteal,
        Stun,
        Exhaust,
        Push,
        EmptyAction,
        ManaBasedAttack,
        LoseHealth,
        EarnManaForEverySoul,
        Erase,   
        DealDamageForEverySoul,
        SpendSouls,
        RandomErase,
        Focus,
        DiscardHand,
        TransformAllCards,
        IncreaseCardDMG,
        IncreaseMaxMana,
        GainSouls,
        HealForEverySoul
    }
}